# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 42e5b60d0ec316fb4b8a027566ff8790c8093102be1aa707676f57e75ab697e63540ecacad04a5153dc401a745b8300e6515dc4fb55e4b3bab25e3011011a02d

test:
  secret_key_base: 08aa3bff4c015eacdb4e9da2fe35efc201c9495c6cd9adb3139e7ad2033298a217dbb0fb473aebed47836b6e95baff6ec384de73b14651b2c58a19200862f343

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
